### ISSUE TITLE
Interleaved parsing in header parameters

### ISSUE THREAD

**Issue by liumaopeng** [aler9/gortsplib#122]
Hello, I used the latest code, but reported another error, which should also be the problem of header parsing. Can you please see what the problem is? thank you

[data.zip](https://github.com/aler9/gortsplib/files/8536180/data.zip)

In addition, if I use VLC player to pull the stream first, I can pull the stream successfully by using gortsplib.But the video is Caton's

**Comment by aler9** [comment]
Hello, can you post the code you're using?

Basically, the problem is that you're sending a SETUP request against this URL

```
rtsp://10.105.240.22:9100/dss/monitor/param/cameraid=1000193%241%26substream=1?token=73397&trackID=0
```

While you should send a SETUP request against

```
rtsp://10.105.240.22:9100/dss/monitor/param/cameraid=1000193%241%26substream=1?token=73397&trackID=0/trackID=0
```

I analyzed the dump you posted and i can assure you that rtsp-simple-server uses the right URL. Therefore, we have to find out why your request uses a different URL, that doesn't take into consideration the control attribute.

**Comment by liumaopeng** [comment]
Sorry, today I followed your instructions and followed the code; Because I read the introduction on the official website of Dahua, which is the last attribute I specially removed. Now I restore it back and it can be used. Thank you very much for your guidance

![4a091067b2363227f85449d37b30fb4](https://user-images.githubusercontent.com/45622638/164951974-b55c9933-4b01-4c1a-a5fe-c0b7256477d3.png)
