### ISSUE TITLE
Something wrong when parseing package,and it will be timeout

### ISSUE THREAD

**Issue by liumaopeng** [aler9/gortsplib#123]
Hello, when I use gortsplib to pull streams, I connect to Dahua dss-h8900 platform, and some stream connection times out (VLC and Dahua plug-ins can be used normally). There may be a problem with the parsing package. The relevant logs are as follows：the ip is from 10.105.243.19 to  10.105 240.22

[2022-04-27T18.log](https://github.com/aler9/gortsplib/files/8578853/2022-04-27T18.log)

[data.zip](https://github.com/aler9/gortsplib/files/8578857/data.zip)

**Comment by aler9** [comment]
Hello, please try to connect to the cameras with rtsp-simple-server and post a log with the option `logLevel: debug`.
Thanks.

**Comment by aler9** [comment]
I tried to analyze the dump but i was not able to find the exact problem, so more infos are needed.

**Comment by liumaopeng** [comment]
OK, but I don't have debugging conditions these days. I'll upload it when I can test it

**Comment by liumaopeng** [comment]
I'm very sorry. I haven't had time to capture packets before. Today, I tested and played two cameras. One can play and the other can't. The packet capturing data is the gortsplib referenced by our service, and the other two log files are printed with RTSP-simple-server
[rtsp-simple-server1.log](https://github.com/aler9/gortsplib/files/8963208/rtsp-simple-server1.log)
[rtsp-simple-server2.log](https://github.com/aler9/gortsplib/files/8963209/rtsp-simple-server2.log)
[rtsp-simple-server.log](https://github.com/aler9/gortsplib/files/8963210/rtsp-simple-server.log)

**Comment by liumaopeng** [comment]
This is the bag caught by my direct camera. It can't be played. The address is: rtsp://admin:admin123 @10.105.240.92:554/cam/realmonitor? Channel=1&subtype=0 the same address can be played using VLC

[test.zip](https://github.com/aler9/gortsplib/files/8963542/test.zip)

**Comment by aler9** [comment]
None of the file you provided gives any hint about the issue. Server logs show that you're trying to publish something with FFmpeg (what's the role of ffmpeg in all this?), while test.zip shows a successful connection from the server to the camera.
Please provide direct proof of the issue, otherwise it can't be solved.
For instance, you may provide
* a network dump of the data exchanged between the server and the camera, when the server is used in proxy mode
* a network dump of the data exchanged between the camera and ffmpeg, when the server is NOT involved and the camera is read directly with ffmpeg

**Comment by liumaopeng** [comment]
Sorry, I tested it again today. You can use rtsp-simple-server to directly access and pull streams. It should not be the problem of gortsplib, but the problem of my plug-in service. Thank you very much.
