### ISSUE TITLE
Adding recording

### ISSUE THREAD

**Issue by Mirabeau2Code** [aler9/gortsplib#137]
Hello Alessandro
Is there a possibility to add methods for saving video streams?
(in this lib or in your rtsp-simple-server project)

For example optional:
- either the constant flow
- either the flow per duration slice (1 file per slice)
- either the "cyclic" flow of a determined duration (save the last hour for example)

thank you for the beautiful work done, it helps me to learn Go ;)

**Comment by aler9** [comment]
Hello, i've added an example that shows how to save incoming streams to disk:
https://github.com/aler9/gortsplib/blob/main/examples/server-h264-save-to-disk/main.go

Since this is a library and not a software, you are free to edit the example in order to implement any of the logic you need (constant flow / cyclic / etc) - just remember that you can close and open .ts files at any time (for instance, every 5 mins)
