### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by dongjialong2006** [aler9/gortsplib#14]
error: bad status code: 401 (Unauthorized) but user name and password are correct

**Comment by dongjialong2006** [comment]
when I alter username or password from right to wrong or from wrong to right

**Comment by dongjialong2006** [comment]
every is ok after restart programm

**Comment by aler9** [comment]
Sorry, but you didn't provide any information that allows me to replicate this bug. i need to know:
* how are you using the library (server mode, client mode) and a sample code that shows how you're using it
* what is the software you're using the library against (a camera? which camera?)

Also, if this is a communication issue between the library and a camera, i need a network dump, that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach
