### ISSUE TITLE
Support custom dialers/listeners

### ISSUE THREAD

**Issue by photostorm** [aler9/gortsplib#2]
The new client conf is too limited for me

**Comment by aler9** [comment]
Hello, i tried to the last to keep the `net.Conn` outside `gortsplib.ClientConn`, but the problem is that a ClientConn owns multiple connections and thread:
* the main RTSP/TCP connection
* multiple RtcpReceivers
* the receiver report goroutine
* multiple ConnClientUdpListeners if connection type is UDP 

Therefore, in my opinion it's better if ClientConn owns everything (and closes everything avoiding leaks).
You can still access the main RTSP/TCP connection by using `ConnClient.NetConn()`.

Let me know if you have a better idea.

**Comment by photostorm** [comment]
I understand your point. Is possible to provide way to support custom Dialer? If that possible then I do not need net.Conn pass in.

**Comment by aler9** [comment]
solved with #3
