### ISSUE TITLE
SDP Mime Types are not case-insensitive

### ISSUE THREAD

**Issue by asleeponduty** [aler9/gortsplib#35]
Per findings in RenderHeads/UnityPlugin-AVProVideo#653 , the MIME type in an SDP is not treated as case-insensitive. 
Some implementations, such as Media Foundation, have issues with this. 
In particular, the "mpeg4-generic" MIME must be lowercase

See here:
https://github.com/aler9/gortsplib/blob/8be64d9cf6ddeee1ec0560ad467724770de928c0/track.go#L152

https://github.com/aler9/gortsplib/blob/8be64d9cf6ddeee1ec0560ad467724770de928c0/track.go#L185

And in your test script
https://github.com/aler9/gortsplib/blob/bd1b88226edb8b088996c522a80b96068d5570ee/track_test.go#L493

https://github.com/aler9/gortsplib/blob/bd1b88226edb8b088996c522a80b96068d5570ee/track_test.go#L522

**Comment by asleeponduty** [comment]
Please note, the original comment does not handle RTSP streams that have been relayed:
The SDP produced by FFMPEG generating an RTSP stream also does not conform to this loose standard for compatibility with Media Foundation. 
As a dirty workaround, I edited the `unmarshalMediaAttribute` function to check for the presence of an all-caps "MPEG4", and convert it to lowercase. 
https://github.com/aler9/gortsplib/blob/49dfd34ede588c38cb6724e68750400e5d2a8d9d/pkg/sdp/sdp.go#L471

In this case, I added it to be the first thing this function checks for. 
```go
        if strings.Contains(value, "MPEG4") {
                value = strings.ToLower(value)
        }
```

Admittedly, this is not the true solution to this problem. If anything, this should be raised to the FFMPEG developers, or whichever library they currently use that is responsible for this. 

My only exposure to Go at this point has been through your library; I'd love to make a PR to fix this but I don't quite have the understanding needed to make sure it passes coverage correctly. 

## Where this leaves us

That being said - The information mentioned in the opening comment allows a Windows Media Foundation software (AVPRO in Unity) to correctly decode audio in RTSP streams generated by this library. This happens whenever a server using this would ingest a stream of another format, such as RTMP. 

The changes noted in this comment allow successful relay of an RTSP stream to the same Media Foundation program, correcting an irregularity in a common stream producer. 

I'd like to hear your thoughts on this - is "Garbage In, Garbage Out" acceptable, or should there be effort to help with compatibility?

**Comment by aler9** [comment]
Hello, since the [specification](https://datatracker.ietf.org/doc/html/rfc3640) always mentions `mpeg4-generic` in lowercase, the library must be changed accordingly.

Please note that this solves the issue only for RTSP streams that have been generated from the ground, for instance RTMP / HLS streams that are converted into RTSP inside rtsp-simple-server, or GStreamer RTP streams that are used in the [client-publish example](https://github.com/aler9/gortsplib/blob/main/examples/client-publish/main.go).

Regarding relayed RTSP streams, at the moment their SDP is left untouched in rtsp-simple-server, and the best solution consists in editing the software that generates them, but i'm evaluating the possibility of inserting a filter inside the server to fix erroneous SDPs.

**Comment by aler9** [comment]
Anyway, this issue doesn't concern gortsplib anymore (it's now a rtsp-simple-server enhancement).
