### ISSUE TITLE
Tracks.Write(): way to preserving more media attributes in SDP 

### ISSUE THREAD

**Issue by nu774** [aler9/gortsplib#49]
Sometimes, we want attributes other than a:rtpmap / a:fmtp, but there's no way to send such SDP in the current interface.

For example, ONVIF streaming spec (https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf) uses a:sendonly / a.recvonly (See section 5.3.2 Connection setup for a bi- directional connection).

**Comment by aler9** [comment]
Hello, Tracks.Write() is used only by the server to generate a clean SDP that is sent to the readers. This SDP must be cleaned since it regulates the communication between a reader and gortsplib's server, and this must not be influenced by any parameter set by the publisher, except for the codec.
It doesn't influence the communication between a publisher and gortsplib, that happens in a separate context with respect to the communication between a reader and gortsplib.
It is not used by the client.
It is not used to communicate with ONVIF devices.
why do you need this feature?

**Comment by nu774** [comment]
I don't think It's usually needed. This is rather an "enhancement request".
And I'm not talking about communicating with existing ONVIF devices.

This is needed when someone wants to implement his own ONVIF compliant RTSP server(device) using your library, since ONVIF server has to send SDP that include a=sendonly or a=recvonly lines.

**Comment by aler9** [comment]
now `tracks.Write()` writes the tracks as they are. 

A cleaning operation is performed during `NewServerStream(tracks)`.

SDP of tracks can then be edited by calling `ServerStream.Tracks()` and editing the tracks.
