### ISSUE TITLE
Add a field to ServerSession where user defined object can be stored

### ISSUE THREAD

**Issue by nu774** [aler9/gortsplib#50]
When users want to keep track of per-session state for the application, users have to maintain per-session map and do mutex lock/map lookup on any subsequent callbacks including OnFrame(), which is expensive.
Why don't you just add a field to ServerSession where users can store any user-defined per-session object?

**Comment by iamdavidcz** [comment]
I believe that this issue has a broader scope and it also applies to other entities as well. For example, I don't believe that currently there is a way to provide user defined `context.Context` to the following entities:

- `gortsplib.Server` (`ctx` is assigned [here](https://github.com/aler9/gortsplib/blob/main/server.go#L313)),
- `gortsplib.ServerConn` (`ctx` is assigned [here](https://github.com/aler9/gortsplib/blob/main/serverconn.go#L55)),
- `gortsplib.ServerSession` (`ctx` is assigned [here](https://github.com/aler9/gortsplib/blob/main/serversession.go#L197)).

So it looks like the original context is created in `(s *Server) Start()` and it is wrapped with `context.WithCancel()` in `newServerConn` and `newServerSession` later on. Anyway, it would be great to have a way of providing user defined context since it would improve usability and extensibility of gortsplib greatly.

**Comment by aler9** [comment]
`SetUserData()` and `UserData()` have been added to `ServerSession`. A type-checking based implementation would have required a significant change in the public API of the library, therefore i decided towards an approach that doesn't require any change in existing code.
